### ISSUE TITLE
¿Como citar esta info?

### ISSUE THREAD

**Issue by mergenthaler** [FedericoGarza/covidmx#1]
Sería bueno agregar la forma correcta de citar este repo.

**Comment by AzulGarza** [comment]
Listo! Ya se puede citar usando: Federico Garza Ramírez. (2020, April 16). covidmx: Python API to get information about COVID-19 in México. (Version 0.2.3). Zenodo. http://doi.org/10.5281/zenodo.3753631. Info disponible también en el README.
