### ISSUE TITLE
Error encoding='UTF-8'

### ISSUE THREAD

**Issue by alanponce** [FedericoGarza/covidmx#10]
covid_dge_data = CovidMX().get_data()

data = pd.read_csv(url_data, encoding='UTF-8')
     73         except BaseException:
---> 74             raise RuntimeError('Cannot read the data.')
     75 
     76         try:

RuntimeError: Cannot read the data.

**Comment by AlexanderBV1** [comment]
Changing the encoding to 'LATIN-1' fixes this issue but i'm unaware if that changes anything relevant inside the information. I haven't seen anything yet but it is a possibility.

**Comment by isccarrasco** [comment]
I have added the validation for avoiding this issue in the open [PR](https://github.com/FedericoGarza/covidmx/pull/11), yes, the `latin` encoding solves the issue, but it seems that it is only for some of the csv files, the source is not consistent in the encoding I think.

**Comment by AzulGarza** [comment]
Thank you! I will prepare the next release considering this change.

**Comment by liubaoryol** [comment]
> Changing the encoding to 'LATIN-1' fixes this issue but i'm unaware if that changes anything relevant inside the information. I haven't seen anything yet but it is a possibility.

How do you change the encoding? I still have this encoding issue with the Dirección General de Epidemiología source.

**Comment by AzulGarza** [comment]
The [version 0.3.0](https://github.com/FedericoGarza/covidmx/#030-current-version) includes this fix. You can upgrade with `pip install --upgrade covidmx`. Let me know if you have any problem.
