### ISSUE TITLE
Catalogos missing

### ISSUE THREAD

**Issue by alanponce** [FedericoGarza/covidmx#8]
When I am calling this line

covid_dge_data = CovidMX().get_data()

I have this error:

"There is no item named 'Catalogos_0412.xlsx' in the archive"

**Comment by AlexanderBV1** [comment]
![image](https://user-images.githubusercontent.com/26008094/79762819-d709f900-82e8-11ea-9684-68048ea69ae4.png)
The name changed for files under the catalogue description. 
This can work as a quick fix in the meantime.

NVM, there were changed in the catalogue too. 
![image](https://user-images.githubusercontent.com/26008094/79763489-c60db780-82e9-11ea-9593-e869a0c73ec0.png)

**Comment by AzulGarza** [comment]
Thank you for your comments! This is now fixed in the [new version 0.2.5](https://pypi.org/project/covidmx/).

[Updates.](https://github.com/FedericoGarza/covidmx#025-current-version)
